name = "dream"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "dream"
database_id = "41c28577-8830-4be0-b581-43d773e7d0e1"
migrations_dir = "src/config/db/migrations_d1"
remote = true

[observability]
enabled = true

[vars]
NEXT_PUBLIC_APP_URL = "https://dream.xiao64702.workers.dev"
NEXT_PUBLIC_APP_NAME = "Dream"
NEXT_PUBLIC_THEME = "default"
NEXT_PUBLIC_APPEARANCE = "system"
DATABASE_PROVIDER = "d1"
DATABASE_URL = ""
DB_SCHEMA_FILE = "./src/config/db/schema.sqlite.ts"
DB_MIGRATIONS_OUT = "./src/config/db/migrations_d1"
DB_SINGLETON_ENABLED = "false"
DB_MAX_CONNECTIONS = "1"
AUTH_SECRET = "1edb7188a2da397638add18aefb13522aae69982901c436e89dedbdfb44991c3"
